# include recommended lints
include: package:lints/recommended.yaml
# ignore some warnings for this project
analyzer:
    errors:
        unused_local_variable: ignore
        dead_code: ignore
        avoid_init_to_null: ignore
